spring:
  datasource:
    name: datasource
    url: jdbc:mysql://192.168.16.246:3306/urule?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ewj3WmSnyPDPrtT5

  jackson:
    default-property-inclusion: non_null

urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
